function patlistbrainmri2ct = importfile(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  PATLISTBRAINMRI2CT = IMPORTFILE1(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  PATLISTBRAINMRI2CT = IMPORTFILE1(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  patlistbrainmri2ct = importfile1("/nfs/rtsan02/userdata/home/mmaspero/Projects/GrandChallenge_sCT/Script_DataOrg/script_mri2ct/pat_list_brain_mri2ct.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 05-Apr-2022 11:58:20

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["PtName", "VarName2", "VarName3", "phase"];
opts.VariableTypes = ["string", "double", "double", "string"];
opts = setvaropts(opts, [1, 4], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 4], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
patlistbrainmri2ct = readtable(filename, opts);

end
